name: homepad
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  responsive_builder: ^0.7.0
  flutter_neumorphic_plus: ^3.3.0
  flutter_svg: ^2.0.9
  bot_toast: ^4.1.3
  virtual_keyboard_multi_language: ^1.0.3
  sqlite3: ^2.3.0
  flutter_slidable: ^3.0.1
  dbus: ^0.7.10
  wakelock_plus: ^1.1.4
  weather: ^3.1.1
  table_calendar: ^3.0.9
  video_player: ^2.8.2
  video_player_elinux:
    git:
      url: https://github.com/sony/flutter-elinux-plugins.git
      path: packages/video_player
      ref: main
  # video_player_elinux:
  #   path: ../video-player

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/video/